// 手动收集的加密货币别名数据
const MANUAL_CRYPTO_SYMBOLS = {
  'HYPE': ['hyperliquid', 'hype'],
  'SUI': ['sui', 'sui'],
  'MOVE': ['movement', 'move'],
  'USUAL': ['usual', 'usual'],
  'EIGEN': ['eigenlayer', 'eigen'],
  'ZK': ['zkSync', 'zk'],
  'W': ['wormhole', 'w'],
  'ENA': ['ethena', 'ena'],
  'ONDO': ['ondo finance', 'ondo'],
  'PENGU': ['pudgy penguins', 'pengu'],
  'VIRTUAL': ['virtuals protocol', 'virtual'],
  'AI16Z': ['ai16z', 'ai16z'],
  'GOAT': ['goatseus maximus', 'goat'],
  'ZEREBRO': ['zerebro', 'zerebro'],
  'FARTCOIN': ['fartcoin', 'fartcoin'],
  'GRASS': ['grass', 'grass'],
  'CHILLGUY': ['just a chill guy', 'chillguy'],
  'ACT': ['act i : the ai prophecy', 'act'],
  'PNUT': ['peanut the squirrel', 'pnut'],
  'TURBO': ['turbo', 'turbo'],
  'BRETT': ['brett', 'brett'],
  'SPX': ['spx6900', 'spx'],
  'NEIRO': ['neiro', 'neiro'],
  'WIF': ['dogwifhat', 'wif'],
  'POPCAT': ['popcat', 'popcat'],
  'MEW': ['cat in a dogs world', 'mew'],
  'MOTHER': ['mother iggy', 'mother'],
  'SLERF': ['slerf', 'slerf'],
  'BOME': ['book of meme', 'bome'],
  'TRUMP': ['official trump', 'trump'],
  'MELANIA': ['melania', 'melania'],
  'DOGE': ['dogecoin', 'doge', '狗狗币'],
  'SHIB': ['shiba inu', 'shib', '柴犬币'],
  'PEPE': ['pepe', 'pepe'],
  'FLOKI': ['floki', 'floki'],
  'BONK': ['bonk', 'bonk'],
  'STRK': ['starknet', 'strk'],
  'MANTA': ['manta network', 'manta'],
  'BLAST': ['blast', 'blast'],
  'MODE': ['mode', 'mode'],
  'LINEA': ['linea', 'linea'],
  'SCROLL': ['scroll', 'scroll'],
  'BASE': ['base', 'base'],
  'ZETA': ['zetachain', 'zeta'],
  'TAIKO': ['taiko', 'taiko'],
  'HNT': ['helium', 'hnt', '氦币'],
  'MOBILE': ['helium mobile', 'mobile'],
  'IOT': ['helium iot', 'iot'],
  'HONEY': ['hivemapper', 'honey'],
  'DIMO': ['dimo', 'dimo'],
  'PYN': ['pylon network', 'pyn'],
  'NATIX': ['natix network', 'natix'],
  'RONIN': ['ronin', 'ronin'],
  'IMX': ['immutable x', 'imx'],
  'MAGIC': ['treasure', 'magic'],
  'PRIME': ['echelon prime', 'prime'],
  'GALA': ['gala', 'gala'],
  'SAND': ['the sandbox', 'sand'],
  'MANA': ['decentraland', 'mana'],
  'ENJ': ['enjin', 'enj', '恩金'],
  'AXS': ['axie infinity', 'axs'],
  'SLP': ['smooth love potion', 'slp'],
  'ALICE': ['my neighbor alice', 'alice'],
  'TLM': ['alien worlds', 'tlm'],
  'GODS': ['gods unchained', 'gods'],
  'SUPER': ['superfarm', 'super'],
  'YGG': ['yield guild games', 'ygg'],
  'GUILD': ['guild fi', 'guild'],
  'MC': ['merit circle', 'mc'],
  'NAKA': ['nakamoto games', 'naka'],
  'SIDUS': ['sidus heroes', 'sidus'],
  'SKILL': ['cryptoblades', 'skill'],
  'JEWEL': ['defi kingdoms', 'jewel'],
  'CRYSTAL': ['crystal token', 'crystal'],
  'DPET': ['my defi pet', 'dpet'],
  'MBOX': ['mobox', 'mbox'],
  'TOWER': ['crazy defense heroes', 'tower'],
  'PYR': ['vulcan forged', 'pyr'],
  'LOKA': ['league of kingdoms', 'loka'],
  'ETERNAL': ['cryptomines eternal', 'eternal'],
  'UFO': ['ufo gaming', 'ufo'],
  'WILD': ['wilder world', 'wild'],
  'STARL': ['starlink', 'starl'],
  'REVV': ['revv', 'revv'],
  'TAO': ['bittensor', 'tao'],
  'FET': ['fetch.ai', 'fet'],
  'AGIX': ['singularitynet', 'agix'],
  'OCEAN': ['ocean protocol', 'ocean'],
  'NMR': ['numerai', 'nmr'],
  'GLM': ['golem', 'glm'],
  'RLC': ['iexec rlc', 'rlc'],
  'CTXC': ['cortex', 'ctxc'],
  'DBC': ['deepbrain chain', 'dbc'],
  'MATRIX': ['matrix ai network', 'matrix'],
  'EFFECT': ['effect.ai', 'effect'],
  'PHB': ['phoenix', 'phb'],
  'COVAL': ['circuits of value', 'coval'],
  'DESO': ['decentralized social', 'deso'],
  'RALLY': ['rally', 'rally'],
  'WHALE': ['whale', 'whale'],
  'ALEX': ['alex', 'alex'],
  'FRIEND': ['friend.tech', 'friend'],
  'SOCIAL': ['social token', 'social'],
  'CREATOR': ['creator economy', 'creator'],
  'CONTENT': ['content protocol', 'content'],
  'MEDIA': ['media protocol', 'media'],
  'STREAM': ['stream token', 'stream'],
  'SCRT': ['secret network', 'scrt'],
  'ROSE': ['oasis network', 'rose'],
  'NYM': ['nym', 'nym'],
  'KEEP': ['keep network', 'keep'],
  'NuCypher': ['nucypher', 'nu'],
  'TORN': ['tornado cash', 'torn'],
  'RAILGUN': ['railgun', 'railgun'],
  'AZTEC': ['aztec', 'aztec'],
  'MINA': ['mina protocol', 'mina'],
  'ALEO': ['aleo', 'aleo'],
  'RDNT': ['radiant capital', 'rdnt'],
  'GMX': ['gmx', 'gmx'],
  'JOE': ['traderjoe', 'joe'],
  'VELO': ['velodrome', 'velo'],
  'BAL': ['balancer', 'bal'],
  'RUNE': ['thorchain', 'rune'],
  'OSMO': ['osmosis', 'osmo'],
  'ATOM': ['cosmos', 'atom', '阿童木'],
  'JUNO': ['juno', 'juno'],
  'LUNA': ['terra luna', 'luna', '月神'],
  'LUNC': ['terra luna classic', 'lunc'],
  'USTC': ['terrausd classic', 'ustc'],
  'KAVA': ['kava', 'kava'],
  'HARD': ['hard protocol', 'hard'],
  'SWP': ['swipe', 'swp'],
  'BNT': ['bancor', 'bnt'],
  'ZRX': ['0x', 'zrx'],
  'LRC': ['loopring', 'lrc', '路印'],
  'KNC': ['kyber network', 'knc'],
  'MLN': ['enzyme', 'mln'],
  'REP': ['augur', 'rep'],
  'MKR': ['maker', 'mkr'],
  'ALPHA': ['alpha finance', 'alpha'],
  'CREAM': ['cream finance', 'cream'],
  'BADGER': ['badger dao', 'badger'],
  'DIGG': ['digg', 'digg'],
  'PICKLE': ['pickle finance', 'pickle'],
  'SOCKS': ['unisocks', 'socks'],
  'DUCK': ['duck dao', 'duck'],
  'VALUE': ['value defi', 'value'],
  'FARM': ['harvest finance', 'farm'],
  'BASK': ['basket dao', 'bask'],
  'INDEX': ['index cooperative', 'index'],
  'DPI': ['defi pulse index', 'dpi'],
  'MVI': ['metaverse index', 'mvi'],
  'DATA': ['streamr', 'data'],
  'BED': ['bankless bed index', 'bed'],
};

export { MANUAL_CRYPTO_SYMBOLS };